### ISSUE TITLE
[fix] 마이페이지 라우터 이동시 css 늦게 불러와짐

### ISSUE THREAD

**Issue by ghost** [prgrms-fe-devcourse/FEDC3_Tripend_JAEHO#62]
## 해야할 일
- 마이페이지 슬라이드바 라우터 이동시 css 한텀 늦게 불러와지는 현상

## 기능 구현
- [x] 마이페이지 슬라이드바 라우터 이동시 css 한텀 늦게 불러와지는 현상 해결

## 예상기간
- 1일

**Comment by Seung-hwan285** [comment]
할 분 추천받습니다..
